Skip dlopen test on Windows for now. (#35)
Logs:
```
[build] [15/123   4% :: 0.278] Building C object CMakeFiles\dlopen-hip.dir\tests\dlopen-hip.c.obj
[build] FAILED: CMakeFiles/dlopen-hip.dir/tests/dlopen-hip.c.obj
[build] ccache C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1442~1.344\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /Zi /O2 /Ob1 /DNDEBUG -MD /showIncludes /FoCMakeFiles\dlopen-hip.dir\tests\dlopen-hip.c.obj /FdCMakeFiles\dlopen-hip.dir\ /FS -c D:\projects\TheRock\tests\dlopen-hip.c
[build] D:\projects\TheRock\tests\dlopen-hip.c(1): fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory
```

The https://github.com/nod-ai/TheRock/blob/main/tests/dlopen-hip.c file
is using a Unix header for `dlopen` of a shared object file. On Windows,
an API like
https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya
is typically used to open a DLL instead.